import { writeFile } from 'node:fs/promises';
import type { DockerBuildConfig } from 'pledgestack-core';

export interface DockerfileOptions {
  /** Node version (default: '20') */
  nodeVersion?: string;
  /** Port to expose (default: 3000) */
  port?: number;
  /** Package manager (default: 'pnpm') */
  packageManager?: 'pnpm' | 'npm' | 'yarn';
  /** Build command (default: 'pledge build') */
  buildCommand?: string;
  /** Start command (default: 'pledge start') */
  startCommand?: string;
  /** Include healthcheck (default: true) */
  healthcheck?: boolean;
  /** Healthcheck path (default: '/health') */
  healthcheckPath?: string;
  /** Output path (default: 'Dockerfile') */
  output?: string;
}

export async function generateDockerfile(options: DockerfileOptions = {}): Promise<string> {
  const {
    nodeVersion = '20',
    port = 3000,
    packageManager = 'pnpm',
    buildCommand = 'pledge build',
    healthcheck = true,
    healthcheckPath = '/health',
    output = 'Dockerfile',
  } = options;

  const installCmd = packageManager === 'pnpm' ? 'pnpm install --frozen-lockfile'
    : packageManager === 'yarn' ? 'yarn install --frozen-lockfile'
    : 'npm ci';

  // The runtime entrypoint uses the configured start command rather than
  // hardcoding `.pledge/server.js`, which breaks when the build emits
  // content-hashed filenames or a non-default outDir. `pledge start` resolves
  // the actual entry point from the build manifest.
  // The container must listen on the EXPOSEd port and on all interfaces:
  // `pledge start` defaults to port 3000 on `localhost`, which is unreachable
  // from outside the container (and ignores a custom `port` option).
  const startCmd = options.startCommand ?? `npx pledge start --port ${port} --hostname 0.0.0.0`;

  const dockerfile = `# Generated by PledgeStack CLI
FROM node:${nodeVersion}-alpine AS base

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app
COPY package.json ${packageManager === 'pnpm' ? 'pnpm-lock.yaml' : packageManager === 'yarn' ? 'yarn.lock' : 'package-lock.json'} ./
RUN ${installCmd}

# Build the application
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN ${buildCommand}

# Production image
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 pledgestack
# pledge start reads pledge.config.* and the app/ routes at runtime, so ship
# the whole build stage (which also works when there is no public/ directory).
COPY --from=builder /app ./
USER pledgestack
EXPOSE ${port}
${healthcheck ? `HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://localhost:${port}${healthcheckPath} || exit 1` : ''}
CMD ["sh", "-c", ${JSON.stringify(startCmd)}]
`;

  await writeFile(output, dockerfile);
  return dockerfile;
}

/**
 * Generates a Rust-addon-optimized, multi-stage Dockerfile (rust-builder →
 * js-builder → runtime) using pledgestack-core's `generateDockerfile`. Unlike
 * the plain single-stage output above, this compiles packages/core/native's
 * Rust crates in a dedicated stage and only ships the resulting .node/.so
 * files (not a Rust toolchain) into the final runtime image — meaningfully
 * smaller and faster for apps that rely on the native SSR/compression/etc.
 * addons. Use `pledge docker --optimized`.
 */
export async function generateOptimizedDockerfile(config: DockerBuildConfig = {}, output = 'Dockerfile'): Promise<string> {
  const { generateDockerfile: generateOptimized } = await import('pledgestack-core');
  const dockerfile = generateOptimized(config);
  // Honor the requested output path instead of always overwriting 'Dockerfile'.
  await writeFile(output, dockerfile);
  return dockerfile;
}

export async function generateOptimizedDockerCompose(config: DockerBuildConfig = {}): Promise<string> {
  const { generateDockerCompose: generateOptimizedCompose } = await import('pledgestack-core');
  const compose = generateOptimizedCompose(config);
  await writeFile('docker-compose.yml', compose);
  return compose;
}

export async function generateDockerIgnore(): Promise<void> {
  const content = `node_modules
.git
.pledge
*.md
.env*
.pledge
coverage
.vscode
`;

  await writeFile('.dockerignore', content);
}

export async function generateDockerCompose(options: { port?: number; imageName?: string } = {}): Promise<string> {
  const { port = 3000, imageName = 'pledgestack-app' } = options;

  const compose = `version: '3.8'
services:
  app:
    image: ${imageName}
    build: .
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${port}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
`;

  await writeFile('docker-compose.yml', compose);
  return compose;
}
