import type { IncomingMessage, ServerResponse } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, relative, sep, isAbsolute } from 'node:path';
import { readdirSync, statSync } from 'node:fs';
import type { PledgeConfig, RendererAdapter, ClientScriptOptions } from 'pledgestack-shared';
import { FILE_CONVENTIONS, getRendererRegistry } from 'pledgestack-shared';

/**
 * Serves PledgeStack virtual modules at /__pledge__/* paths.
 *
 * - /__pledge__/client.css → served from .pledge/__pledge__/client.css
 * - /__pledge__/client.js → generated ESM hydration module (framework-specific)
 * - /__pledge__/rsc-client.js → generated RSC client module (React only)
 *
 * The client hydration script is generated by the active renderer adapter,
 * making it framework-agnostic. Each adapter (React, Vue, Solid, Svelte)
 * generates the appropriate hydration code.
 */
export async function tryServePledgeVirtual(
  req: IncomingMessage,
  res: ServerResponse,
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): Promise<boolean> {
  const url = req.url ?? '/';
  const pathname = url.split('?')[0];
  // '/_pledge/image' (query form, emitted by pledgestack-image) lives outside
  // the /__pledge__/ prefix — the early return used to make it unreachable.
  if (!url.startsWith('/__pledge__/') && pathname !== '/_pledge/image') return false;

  if (pathname === '/__pledge__/client.css') {
    return serveClientCss(res, config);
  }

  if (pathname === '/__pledge__/client.js') {
    return serveClientJs(res, config, isDev, pledgepackPort);
  }

  if (pathname === '/__pledge__/rsc-client.js') {
    return serveRscClientJs(res, config, isDev, pledgepackPort);
  }

  // Font optimization endpoint — serves optimized font CSS
  if (pathname.startsWith('/__pledge__/font/')) {
    return serveFontCss(req, res, config, pathname);
  }

  // Image optimization endpoint — serves optimized/resized images. Accepts both
  // the path form (/__pledge__/image/<path>) and the query form
  // (/_pledge/image?src=<path>) emitted by the pledgestack-image package.
  if (pathname.startsWith('/__pledge__/image/') || pathname === '/_pledge/image') {
    return serveOptimizedImage(req, res, config, pathname);
  }

  if (pathname === '/__pledge__/action') {
    return false;
  }

  return false;
}

/**
 * Serves optimized font CSS at /__pledge__/font/:family
 * Generates @font-face declarations with preload hints.
 */
async function serveFontCss(
  _req: IncomingMessage,
  res: ServerResponse,
  _config: PledgeConfig,
  pathname: string,
): Promise<boolean> {
  try {
    // pledgestack-font is an optional dependency — built from a variable
    // specifier so TS treats this as an untyped dynamic import instead of
    // pulling the whole package into server's compile graph.
    const fontModuleName: string = 'pledgestack-font';
    const { resolveFont, fontVarName } = await import(fontModuleName);
    const family = decodeURIComponent(pathname.replace('/__pledge__/font/', ''));
    // The family name is interpolated into CSS below — restrict it to plain
    // font-name characters so it can't break out of the quoted string.
    if (!/^[A-Za-z0-9 _-]{1,100}$/.test(family)) throw new Error('Invalid font family');
    const resolved = resolveFont({ family, src: family });
    const css = `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
}
.${fontVarName(family)} { font-family: '${family}', ${resolved.fallbackStack}; }`;
    res.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8', 'Cache-Control': 'public, max-age=86400' });
    res.end(css);
    return true;
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Font not found');
    return true;
  }
}

/**
 * Serves optimized images at /__pledge__/image/:path?w=&h=&format=
 * Resizes and converts images on the fly.
 */
function contentTypeForExt(ext: string): string {
  switch (ext.toLowerCase()) {
    case 'png': return 'image/png';
    case 'jpg': case 'jpeg': return 'image/jpeg';
    case 'webp': return 'image/webp';
    case 'avif': return 'image/avif';
    case 'gif': return 'image/gif';
    case 'svg': return 'image/svg+xml';
    default: return 'application/octet-stream';
  }
}

/** Resolve the source image path within publicDir, rejecting traversal. */
function resolveImageSource(config: PledgeConfig, imagePath: string): string | null {
  const publicDir = join(config.rootDir, config.publicDir);
  const full = join(publicDir, imagePath.replace(/^\/+/, ''));
  const rel = relative(publicDir, full);
  if (rel.startsWith('..') || isAbsolute(rel)) return null;
  return full;
}

async function serveOptimizedImage(
  req: IncomingMessage,
  res: ServerResponse,
  config: PledgeConfig,
  pathname: string,
): Promise<boolean> {
  try {
    const url = new URL(req.url ?? '', 'http://localhost');
    // Source: from the path (path form) or the `src` query param (query form).
    const imagePath = pathname === '/_pledge/image'
      ? (url.searchParams.get('src') ?? '')
      : pathname.replace('/__pledge__/image/', '');
    if (!imagePath) {
      res.writeHead(400, { 'Content-Type': 'text/plain' });
      res.end('Missing image source');
      return true;
    }

    // Only image files, never dotfiles: this endpoint reads straight from
    // public/, so without the allowlist it would serve .env/.git/etc. that
    // the static handler deliberately blocks.
    const imageExt = imagePath.split('?')[0].split('.').pop()?.toLowerCase() ?? '';
    const hasDotSegment = imagePath.split(/[\\/]/).some((s) => s.startsWith('.'));
    if (hasDotSegment || !['png', 'jpg', 'jpeg', 'webp', 'avif', 'gif', 'svg'].includes(imageExt)) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Image not found');
      return true;
    }

    const publicPath = resolveImageSource(config, imagePath);
    const { readFile } = await import('node:fs/promises');
    const { existsSync } = await import('node:fs');
    if (!publicPath || !existsSync(publicPath)) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Image not found');
      return true;
    }

    const data = await readFile(publicPath);
    const srcExt = imagePath.split('.').pop()?.toLowerCase() ?? '';
    // Clamp width/height/quality to safe ranges to prevent DoS via huge resizes.
    const MAX_DIMENSION = 4096;
    const rawWidth = url.searchParams.get('w') ? parseInt(url.searchParams.get('w')!, 10) : undefined;
    const rawHeight = url.searchParams.get('h') ? parseInt(url.searchParams.get('h')!, 10) : undefined;
    const width = rawWidth ? Math.min(Math.max(1, rawWidth), MAX_DIMENSION) : undefined;
    const height = rawHeight ? Math.min(Math.max(1, rawHeight), MAX_DIMENSION) : undefined;
    const rawQuality = url.searchParams.get('q') ? parseInt(url.searchParams.get('q')!, 10) : undefined;
    const quality = rawQuality ? Math.min(Math.max(1, rawQuality), 100) : undefined;
    // Validate format against an allowlist to prevent passing arbitrary strings to sharp.
    const ALLOWED_FORMATS = ['jpeg', 'png', 'webp', 'avif', 'gif', 'tiff'];
    const rawFormat = url.searchParams.get('format') ?? undefined;
    const format = rawFormat && ALLOWED_FORMATS.includes(rawFormat.toLowerCase()) ? rawFormat.toLowerCase() : undefined;

    // Real resize/convert via sharp when it's installed and a transform was
    // requested. When sharp isn't available (or nothing to do), serve the
    // original bytes with the content-type of the ACTUAL file — never claiming a
    // format we didn't convert to (the previous code mislabeled every response).
    if ((width || height || format) && srcExt !== 'svg') {
      // Decompression-bomb guard: a few-hundred-KB PNG can decode to
      // gigabytes of pixels. Cap input bytes and let libvips cap decoded
      // area before spending memory on it.
      const MAX_SOURCE_BYTES = 50 * 1024 * 1024;
      if (data.byteLength > MAX_SOURCE_BYTES) {
        res.writeHead(413, { 'Content-Type': 'text/plain' });
        res.end('Image source too large');
        return true;
      }
      try {
        const sharpMod = 'sharp';
        const sharp = (await import(sharpMod)).default as (input: Buffer, opts?: { limitInputPixels?: number }) => {
          resize: (opts: { width?: number; height?: number; fit: string }) => ReturnType<typeof sharp>;
          toFormat: (fmt: string, opts?: { quality?: number }) => ReturnType<typeof sharp>;
          toBuffer: () => Promise<Buffer>;
        };
        let pipeline = sharp(data, { limitInputPixels: 100_000_000 });
        if (width || height) pipeline = pipeline.resize({ width, height, fit: 'inside' });
        const outFormat = format ?? srcExt;
        pipeline = pipeline.toFormat(outFormat, quality ? { quality } : undefined);
        const out = await pipeline.toBuffer();
        res.writeHead(200, {
          'Content-Type': contentTypeForExt(outFormat),
          'Cache-Control': 'public, max-age=31536000, immutable',
          'Vary': 'Accept',
        });
        res.end(out);
        return true;
      } catch {
        // sharp not installed — fall through to serving the original.
      }
    }

    res.writeHead(200, {
      'Content-Type': contentTypeForExt(srcExt),
      'Cache-Control': 'public, max-age=31536000, immutable',
      'Vary': 'Accept',
      // SVG passthrough can carry <script> — same-origin navigation to an
      // image/svg+xml response executes it in first-party context.
      ...(srcExt === 'svg' ? { 'Content-Security-Policy': "script-src 'none'; object-src 'none'" } : {}),
    });
    res.end(data);
    return true;
  } catch {
    res.writeHead(500, { 'Content-Type': 'text/plain' });
    res.end('Image optimization failed');
    return true;
  }
}

/**
 * Gets the active renderer adapter, falling back to the registry's default.
 */
function getActiveRenderer(config: PledgeConfig): RendererAdapter | null {
  const registry = getRendererRegistry();
  const framework = config.framework ?? 'react';
  let adapter = registry.get(framework);
  if (!adapter) {
    adapter = registry.getDefault();
  }
  return adapter ?? null;
}

/**
 * Serves the /__pledge_router virtual module.
 *
 * This intercepts the router module generation from PledgePack's Rust dev server
 * to fix a bug where route.ts API files were imported with `import default`,
 * but API routes use named exports (GET, POST, etc.) — no default export.
 *
 * The generated module:
 *   - Imports `default` from page/layout/error/loading/not-found files
 *   - Imports named exports (GET, POST, PUT, DELETE, PATCH) from route.ts files
 *   - Exports a route map for client-side navigation
 */
/** Mirrors pledgestack-client's routeMapKey (server does not depend on client). */
function routeMapKey(convention: string, pattern: string): string {
  return convention === 'page' || convention === 'route' ? pattern : `${convention}:${pattern}`;
}

export function tryServeRouterModule(
  req: IncomingMessage,
  res: ServerResponse,
  config: PledgeConfig,
): boolean {
  const url = req.url ?? '/';
  const pathname = url.split('?')[0];

  if (pathname !== '/__pledge_router') return false;

  const appDir = join(config.rootDir, config.appDir);
  const files = scanRouteFiles(appDir);
  const imports: string[] = [];
  const routeEntries: string[] = [];

  for (const file of files) {
    const importPath = `/${file.relativePath}`;

    if (file.convention === FILE_CONVENTIONS.route) {
      const varName = `route_${routeEntries.length}`;
      imports.push(`import * as ${varName} from '${importPath}';`);
      routeEntries.push(`  ${JSON.stringify(routeMapKey('route', file.routePattern))}: { type: 'api', handlers: ${varName} }`);
    } else {
      const varName = `mod_${routeEntries.length}`;
      imports.push(`import ${varName} from '${importPath}';`);
      const conventionType = file.convention ?? 'page';
      // Non-page conventions are key-prefixed (e.g. "layout:/") so a layout and
      // a page at the same pattern don't overwrite each other in the map.
      const key = routeMapKey(conventionType, file.routePattern);
      routeEntries.push(`  ${JSON.stringify(key)}: { type: ${JSON.stringify(conventionType)}, component: ${varName} }`);
    }
  }

  const code = `// PledgeStack router (auto-generated)
// Re-export the client runtime so the generated client script can import
// everything it needs from '/__pledge_router' (previously RouterProvider/Link
// were imported from here but never exported, breaking client hydration).
export { RouterProvider, Link, resolveRouteElement, resolveRouteChain, initPledgeHydration } from 'pledgestack-client';
${imports.join('\n')}

export const routes = {
${routeEntries.join(',\n')}
};
`;

  res.writeHead(200, {
    'Content-Type': 'application/javascript; charset=utf-8',
    'Cache-Control': 'no-cache',
  });
  res.end(code);
  return true;
}

interface RouteFileInfo {
  relativePath: string;
  convention: string | null;
  routePattern: string;
}

function scanRouteFiles(appDir: string): RouteFileInfo[] {
  const results: RouteFileInfo[] = [];

  function walk(dir: string, prefix: string) {
    let entries;
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = join(dir, entry);
      let stat;
      try {
        stat = statSync(fullPath);
      } catch {
        continue;
      }

      if (stat.isDirectory()) {
        if (entry.startsWith('.') || entry === 'node_modules') continue;
        let segment = entry;
        if (/^\([^)]+\)$/.test(segment)) segment = '';
        if (segment.startsWith('@')) segment = '';
        walk(fullPath, prefix + '/' + segment);
      } else if (stat.isFile() && /\.(tsx|ts|jsx|js)$/.test(entry)) {
        const base = entry.replace(/\.(tsx|ts|jsx|js)$/, '');
        const convention = base in FILE_CONVENTIONS ? base : null;
        if (!convention) continue;

        const relPath = relative(appDir, fullPath).split(sep).join('/');
        let pattern = prefix || '/';
        pattern = pattern.replace(/\/+/g, '/') || '/';
        if (pattern.endsWith('/') && pattern !== '/') {
          pattern = pattern.slice(0, -1);
        }

        results.push({ relativePath: relPath, convention, routePattern: pattern });
      }
    }
  }

  walk(appDir, '');
  return results;
}

async function serveClientCss(
  res: ServerResponse,
  config: PledgeConfig,
): Promise<boolean> {
  const content = await readClientCss(config);
  res.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8' });
  res.end(content ?? '/* PledgeStack — no client CSS */');
  return true;
}

function serveClientJs(
  res: ServerResponse,
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): boolean {
  res.writeHead(200, {
    'Content-Type': 'application/javascript; charset=utf-8',
    'Cache-Control': 'no-cache',
  });
  res.end(generateClientScriptCode(config, isDev, pledgepackPort));
  return true;
}

function serveRscClientJs(
  res: ServerResponse,
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): boolean {
  res.writeHead(200, {
    'Content-Type': 'application/javascript; charset=utf-8',
    'Cache-Control': 'no-cache',
  });
  res.end(generateRscClientScriptCode(config, isDev, pledgepackPort));
  return true;
}

// ---------------------------------------------------------------------------
// Shared generators + SRI integrity hashes
//
// The HTML render pipeline stamps integrity="sha384-…" on the /__pledge__/*
// script/link tags it emits. The hashes are computed here from the SAME code
// path that serves the bytes, so the stamped hash always matches what the
// server actually returns.
// ---------------------------------------------------------------------------

/** Reads the built client CSS, or null when no stylesheet was emitted. */
async function readClientCss(config: PledgeConfig): Promise<string | null> {
  const cssPath = join(config.rootDir, config.outDir, '__pledge__', 'client.css');
  try {
    return await readFile(cssPath, 'utf-8');
  } catch {
    return null;
  }
}

/** Generates the exact bytes served at /__pledge__/client.js. */
export function generateClientScriptCode(config: PledgeConfig, isDev: boolean, pledgepackPort?: number): string {
  const adapter = getActiveRenderer(config);
  const options: ClientScriptOptions = {
    isDev,
    pledgepackPort,
    rscEnabled: config.rsc,
  };
  if (adapter) {
    return adapter.generateClientScript(options);
  }
  return generateFallbackClientScript(options);
}

/** Generates the exact bytes served at /__pledge__/rsc-client.js. */
export function generateRscClientScriptCode(config: PledgeConfig, isDev: boolean, pledgepackPort?: number): string {
  const adapter = getActiveRenderer(config);
  const options: ClientScriptOptions = {
    isDev,
    pledgepackPort,
    rscEnabled: config.rsc,
  };
  if (adapter?.generateRSCClientScript) {
    return adapter.generateRSCClientScript(options);
  }
  return `// PledgeStack RSC client — RSC is not supported for framework "${config.framework ?? 'react'}"\n`;
}

/** SHA-384 SRI hash. Uses WebCrypto so it works in Node and edge runtimes. */
async function sriHash(content: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-384', new TextEncoder().encode(content));
  let binary = '';
  for (const b of new Uint8Array(digest)) binary += String.fromCharCode(b);
  return `sha384-${btoa(binary)}`;
}

/**
 * Computes SRI integrity hashes for the framework-emitted virtual assets
 * (`/__pledge__/client.js`, `/__pledge__/rsc-client.js`, `/__pledge__/client.css`).
 * Keyed by URL path; passed to renderers via RenderSecurity.assetIntegrity.
 * Called once per handler context — results are stable for a given
 * (config, isDev, pledgepackPort) and recomputed after invalidate().
 */
export async function computeAssetIntegrity(
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): Promise<Record<string, string>> {
  const integrity: Record<string, string> = {};
  try {
    integrity['/__pledge__/client.js'] = await sriHash(generateClientScriptCode(config, isDev, pledgepackPort));
    integrity['/__pledge__/rsc-client.js'] = await sriHash(generateRscClientScriptCode(config, isDev, pledgepackPort));
    const css = await readClientCss(config);
    if (css !== null) {
      integrity['/__pledge__/client.css'] = await sriHash(css);
    }
  } catch {
    // Hashing must never break serving — return whatever was computed.
  }
  return integrity;
}

/**
 * Fallback client script when no renderer adapter is registered.
 * This is a minimal hydration that at least calls hydrateRoot for React.
 */
function generateFallbackClientScript(options: ClientScriptOptions): string {
  const { isDev, pledgepackPort } = options;
  const reactImport = isDev && pledgepackPort
    ? `http://localhost:${pledgepackPort}/node_modules/.vite/react.js`
    : 'react';
  const reactDomClientImport = isDev && pledgepackPort
    ? `http://localhost:${pledgepackPort}/node_modules/.vite/react-dom/client.js`
    : 'react-dom/client';

  return `// PledgeStack client hydration (fallback — no renderer adapter registered)
import { hydrateRoot } from '${reactDomClientImport}';
import { createElement } from '${reactImport}';

const root = document.getElementById('__pledge_root__');
if (root) {
  // Hydrate the SSR content — the DOM already has the rendered HTML
  // We hydrate with an empty tree since the content is already there
  try {
    hydrateRoot(root, createElement('div', { id: '__pledge_root__' }));
  } catch (e) {
    console.error('[pledgestack] Hydration error:', e);
  }
}
`;
}
