import type { IncomingMessage, ServerResponse } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { readdirSync, statSync } from 'node:fs';
import type { PledgeConfig, RendererAdapter, ClientScriptOptions } from 'pledgestack-shared';
import { FILE_CONVENTIONS, getRendererRegistry } from 'pledgestack-shared';

/**
 * Serves PledgeStack virtual modules at /__pledge__/* paths.
 *
 * - /__pledge__/client.css → served from .pledge/__pledge__/client.css
 * - /__pledge__/client.js → generated ESM hydration module (framework-specific)
 * - /__pledge__/rsc-client.js → generated RSC client module (React only)
 *
 * The client hydration script is generated by the active renderer adapter,
 * making it framework-agnostic. Each adapter (React, Vue, Solid, Svelte)
 * generates the appropriate hydration code.
 */
export async function tryServePledgeVirtual(
  req: IncomingMessage,
  res: ServerResponse,
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): Promise<boolean> {
  const url = req.url ?? '/';
  if (!url.startsWith('/__pledge__/')) return false;

  const pathname = url.split('?')[0];

  if (pathname === '/__pledge__/client.css') {
    return serveClientCss(res, config);
  }

  if (pathname === '/__pledge__/client.js') {
    return serveClientJs(res, config, isDev, pledgepackPort);
  }

  if (pathname === '/__pledge__/rsc-client.js') {
    return serveRscClientJs(res, config, isDev, pledgepackPort);
  }

  // Font optimization endpoint — serves optimized font CSS
  if (pathname.startsWith('/__pledge__/font/')) {
    return serveFontCss(req, res, config, pathname);
  }

  // Image optimization endpoint — serves optimized/resized images
  if (pathname.startsWith('/__pledge__/image/')) {
    return serveOptimizedImage(req, res, config, pathname);
  }

  if (pathname === '/__pledge__/action') {
    return false;
  }

  return false;
}

/**
 * Serves optimized font CSS at /__pledge__/font/:family
 * Generates @font-face declarations with preload hints.
 */
async function serveFontCss(
  _req: IncomingMessage,
  res: ServerResponse,
  _config: PledgeConfig,
  pathname: string,
): Promise<boolean> {
  try {
    const { resolveFont, fontVarName } = await import('pledgestack-font');
    const family = decodeURIComponent(pathname.replace('/__pledge__/font/', ''));
    const resolved = resolveFont({ family, src: family });
    const css = `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
}
.${fontVarName(family)} { font-family: '${family}', ${resolved.fallbackStack}; }`;
    res.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8', 'Cache-Control': 'public, max-age=86400' });
    res.end(css);
    return true;
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Font not found');
    return true;
  }
}

/**
 * Serves optimized images at /__pledge__/image/:path?w=&h=&format=
 * Resizes and converts images on the fly.
 */
async function serveOptimizedImage(
  req: IncomingMessage,
  res: ServerResponse,
  config: PledgeConfig,
  pathname: string,
): Promise<boolean> {
  try {
    const imagePath = pathname.replace('/__pledge__/image/', '');
    const publicPath = join(config.rootDir, config.publicDir, imagePath);
    const { readFile } = await import('node:fs/promises');
    const { existsSync } = await import('node:fs');
    if (!existsSync(publicPath)) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Image not found');
      return true;
    }
    const data = await readFile(publicPath);
    const url = new URL(req.url ?? '', 'http://localhost');
    const format = url.searchParams.get('format') ?? 'webp';
    // For now, serve the original image — full optimization would use sharp
    const ext = imagePath.split('.').pop()?.toLowerCase() ?? '';
    const contentType = format === 'webp' ? 'image/webp' : format === 'avif' ? 'image/avif' : ext === 'png' ? 'image/png' : ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg' : ext === 'svg' ? 'image/svg+xml' : 'application/octet-stream';
    res.writeHead(200, {
      'Content-Type': contentType,
      'Cache-Control': 'public, max-age=31536000, immutable',
      'Vary': 'Accept',
    });
    res.end(data);
    return true;
  } catch {
    res.writeHead(500, { 'Content-Type': 'text/plain' });
    res.end('Image optimization failed');
    return true;
  }
}

/**
 * Gets the active renderer adapter, falling back to the registry's default.
 */
function getActiveRenderer(config: PledgeConfig): RendererAdapter | null {
  const registry = getRendererRegistry();
  const framework = config.framework ?? 'react';
  let adapter = registry.get(framework);
  if (!adapter) {
    adapter = registry.getDefault();
  }
  return adapter ?? null;
}

/**
 * Serves the /__pledge_router virtual module.
 *
 * This intercepts the router module generation from PledgePack's Rust dev server
 * to fix a bug where route.ts API files were imported with `import default`,
 * but API routes use named exports (GET, POST, etc.) — no default export.
 *
 * The generated module:
 *   - Imports `default` from page/layout/error/loading/not-found files
 *   - Imports named exports (GET, POST, PUT, DELETE, PATCH) from route.ts files
 *   - Exports a route map for client-side navigation
 */
export function tryServeRouterModule(
  req: IncomingMessage,
  res: ServerResponse,
  config: PledgeConfig,
): boolean {
  const url = req.url ?? '/';
  const pathname = url.split('?')[0];

  if (pathname !== '/__pledge_router') return false;

  const appDir = join(config.rootDir, config.appDir);
  const files = scanRouteFiles(appDir);
  const imports: string[] = [];
  const routeEntries: string[] = [];

  for (const file of files) {
    const importPath = `/${file.relativePath}`;

    if (file.convention === FILE_CONVENTIONS.route) {
      const varName = `route_${routeEntries.length}`;
      imports.push(`import * as ${varName} from '${importPath}';`);
      routeEntries.push(`  ${JSON.stringify(file.routePattern)}: { type: 'api', handlers: ${varName} }`);
    } else {
      const varName = `mod_${routeEntries.length}`;
      imports.push(`import ${varName} from '${importPath}';`);
      const conventionType = file.convention ?? 'page';
      routeEntries.push(`  ${JSON.stringify(file.routePattern)}: { type: ${JSON.stringify(conventionType)}, component: ${varName} }`);
    }
  }

  const code = `// PledgeStack router (auto-generated)
${imports.join('\n')}

export const routes = {
${routeEntries.join(',\n')}
};
`;

  res.writeHead(200, {
    'Content-Type': 'application/javascript; charset=utf-8',
    'Cache-Control': 'no-cache',
  });
  res.end(code);
  return true;
}

interface RouteFileInfo {
  relativePath: string;
  convention: string | null;
  routePattern: string;
}

function scanRouteFiles(appDir: string): RouteFileInfo[] {
  const results: RouteFileInfo[] = [];

  function walk(dir: string, prefix: string) {
    let entries;
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = join(dir, entry);
      let stat;
      try {
        stat = statSync(fullPath);
      } catch {
        continue;
      }

      if (stat.isDirectory()) {
        if (entry.startsWith('.') || entry === 'node_modules') continue;
        let segment = entry;
        if (/^\([^)]+\)$/.test(segment)) segment = '';
        if (segment.startsWith('@')) segment = '';
        walk(fullPath, prefix + '/' + segment);
      } else if (stat.isFile() && /\.(tsx|ts|jsx|js)$/.test(entry)) {
        const base = entry.replace(/\.(tsx|ts|jsx|js)$/, '');
        const convention = base in FILE_CONVENTIONS ? base : null;
        if (!convention) continue;

        const relPath = relative(appDir, fullPath).split(sep).join('/');
        let pattern = prefix || '/';
        pattern = pattern.replace(/\/+/g, '/') || '/';
        if (pattern.endsWith('/') && pattern !== '/') {
          pattern = pattern.slice(0, -1);
        }

        results.push({ relativePath: relPath, convention, routePattern: pattern });
      }
    }
  }

  walk(appDir, '');
  return results;
}

async function serveClientCss(
  res: ServerResponse,
  config: PledgeConfig,
): Promise<boolean> {
  const cssPath = join(config.rootDir, config.outDir, '__pledge__', 'client.css');
  try {
    const content = await readFile(cssPath, 'utf-8');
    res.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8' });
    res.end(content);
    return true;
  } catch {
    res.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8' });
    res.end('/* PledgeStack — no client CSS */');
    return true;
  }
}

function serveClientJs(
  res: ServerResponse,
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): boolean {
  const adapter = getActiveRenderer(config);
  const options: ClientScriptOptions = {
    isDev,
    pledgepackPort,
    rscEnabled: config.rsc,
  };

  let code: string;
  if (adapter) {
    // Use the framework-specific hydration script from the renderer adapter
    code = adapter.generateClientScript(options);
  } else {
    // Fallback: minimal hydration script
    code = generateFallbackClientScript(options);
  }

  res.writeHead(200, {
    'Content-Type': 'application/javascript; charset=utf-8',
    'Cache-Control': 'no-cache',
  });
  res.end(code);
  return true;
}

function serveRscClientJs(
  res: ServerResponse,
  config: PledgeConfig,
  isDev: boolean,
  pledgepackPort?: number,
): boolean {
  const adapter = getActiveRenderer(config);
  const options: ClientScriptOptions = {
    isDev,
    pledgepackPort,
    rscEnabled: config.rsc,
  };

  let code: string;
  if (adapter?.generateRSCClientScript) {
    // Use the framework-specific RSC client script (React only)
    code = adapter.generateRSCClientScript(options);
  } else {
    // No RSC support for this framework — emit a no-op
    code = `// PledgeStack RSC client — RSC is not supported for framework "${config.framework ?? 'react'}"\n`;
  }

  res.writeHead(200, {
    'Content-Type': 'application/javascript; charset=utf-8',
    'Cache-Control': 'no-cache',
  });
  res.end(code);
  return true;
}

/**
 * Fallback client script when no renderer adapter is registered.
 * This is a minimal hydration that at least calls hydrateRoot for React.
 */
function generateFallbackClientScript(options: ClientScriptOptions): string {
  const { isDev, pledgepackPort } = options;
  const reactImport = isDev && pledgepackPort
    ? `http://localhost:${pledgepackPort}/node_modules/.vite/react.js`
    : 'react';
  const reactDomClientImport = isDev && pledgepackPort
    ? `http://localhost:${pledgepackPort}/node_modules/.vite/react-dom/client.js`
    : 'react-dom/client';

  return `// PledgeStack client hydration (fallback — no renderer adapter registered)
import { hydrateRoot } from '${reactDomClientImport}';
import { createElement } from '${reactImport}';

const root = document.getElementById('__pledge_root__');
if (root) {
  // Hydrate the SSR content — the DOM already has the rendered HTML
  // We hydrate with an empty tree since the content is already there
  try {
    hydrateRoot(root, createElement('div', { id: '__pledge_root__' }));
  } catch (e) {
    console.error('[pledgestack] Hydration error:', e);
  }
}
`;
}
